# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Stephanie A. Coronel
tagline:          ' '
description:      'Research website'
url:              https://stephcoronel.github.io
baseurl:          /MySite/
repository:		  "stephcoronel/MySite"
author:
  name:           'Stephanie A. Coronel'
  url:            https://twitter.com/steph_a_coronel

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stephcoronel/MySite

theme: jekyll-theme-minimal
