# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins: ['jekyll-twitter-plugin']

# Permalinks
permalink:        pretty

# Setup
title:            Stephanie A. Coronel
tagline:          'Research'
description:      'Research website'
url:              https://stephcoronel.github.io
baseurl:          /MySite/
repository:		  "stephcoronel/MySite"
author:
  name:           'Stephanie A. Coronel'
  url:            https://twitter.com/steph_a_coronel

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

paginate:         5
include:
    - _pages
# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/stephcoronel/MySite

theme: jekyll-theme-minimal
